/**
 * Self-host the Google Fonts the site uses (Archivo variable, Instrument Sans, Spline Sans Mono) so
 * there's no third-party request on load (privacy + one fewer connection). One-off, run when the font
 * set changes: node scripts/fetch-fonts.mjs → assets/fonts/*.woff2 + assets/fonts.css.
 * The site then links assets/fonts.css instead of fonts.googleapis.com.
 */
import { writeFileSync, mkdirSync } from "node:fs";

const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const CSS_URL = "https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Instrument+Sans:wght@400;500;600&family=Spline+Sans+Mono:wght@400;500;700&display=swap";

mkdirSync("assets/fonts", { recursive: true });
let css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// each @font-face carries a comment naming the subset (e.g. /* latin-ext */) before it
const blocks = css.split("@font-face").slice(1);
const counters = {};
let out = `/* Self-hosted fonts (generated by scripts/fetch-fonts.mjs) — Archivo, Instrument Sans, Spline Sans Mono */\n`;
let n = 0;
for (const raw of blocks) {
  const block = "@font-face" + raw.split("@font-face")[0];
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
  const url = (block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/) || [])[1];
  if (!url) { out += block; continue; }
  const slug = fam.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  counters[slug] = (counters[slug] || 0) + 1;
  const file = `${slug}-${counters[slug]}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(`assets/fonts/${file}`, buf);
  n++;
  out += block.replace(url, `assets/fonts/${file}`);
}
writeFileSync("assets/fonts.css", out.trim() + "\n");
console.log(`downloaded ${n} woff2 files → assets/fonts/, wrote assets/fonts.css`);
